version: '3.1'  
services:
  webserver:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - tomcatOne
     - tomcatTwo
     - tomcatThree
 
  tomcatOne:
    image: tomcat
    volumes:
      - ./server.xml:/usr/local/tomcat/conf/server.xml
      - ./ROOT:/usr/local/tomcat/webapps/ROOT
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    ports:
     - 8081:8080
  
  tomcatTwo:
    image: tomcat
    volumes:
     - ./server.xml:/usr/local/tomcat/conf/server.xml
     - ./ROOT:/usr/local/tomcat/webapps/ROOT
     - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    ports:
     - 8082:8080
 
  tomcatThree:
    image: tomcat
    volumes:
     - ./server.xml:/usr/local/tomcat/conf/server.xml
     - ./ROOT:/usr/local/tomcat/webapps/ROOT
     - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    ports:
     - 8083:8080
