
version: '3.3'

services:

  nginx:
      image: nginx
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
          - 80:80
      restart: always



  webserver:
      image: httpd
      volumes:
          - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      restart: always
      depends_on:
          - nginx
  


  personapi:
        image: madhukargunda/spring-boot-personapi
        restart: always
        depends_on:
          - webserver
        deploy:
          replicas: 2
  

