version: '3'
 
services:
  my_mysql:
    image: mysql
    container_name: myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'user'
      MYSQL_DATABASE: 'userdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
    volumes:
      - '/Users/madhukar/mysql-data:/var/lib/mysql'
    restart: always
    ports:
     - '7001:3306'

    