    version: '3'

    service:

    personapi:
        image: madhukargunda/spring-boot-personapi
        restart: always
        #ports:
         #   - 8086:8080
        #depends_on:
         #   - hsapi    

    webserver:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        restart: always
        depends_on:
            - personapi

    apache:       
        image: httpd:alpine
        restart: always
        depends_on:
            - reverseproxy        