version: '3.3'

services:
  demo-mysql:
    image: mysql:latest
    container_name: my_mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD:-p4SSW0rd}
      - MYSQL_DATABASE=${DATABASE_NAME:-demo}
      - MYSQL_USER=${DATABASE_USER:-dbuser}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-dbp4ss}
    ports:
      - 3306:3306
    volumes:
      - /docker-volumes= /var/lib/mysql
